---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: nvidia-device-plugin
      version: 0.14.0
      sourceRef:
        kind: HelmRepository
        name: nvidia-device-plugin
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: nvcr.io/nvidia/k8s-device-plugin
      tag: v0.14.0
    runtimeClassName: nvidia
    nodeSelector:
      node-role.kubernetes.io/nvidia-gpu: "true"
